### GET Products

GET http://localhost:8080/api/products

### GET Product ID

GET http://localhost:8080/api/products/67a03133be2c0dc3707701c5

### POST Products

POST http://localhost:8080/api/products
Content-Type: application/json

{
  "title": "Sidra",
  "description": "Descripción Sidra Tunuyan",
  "code": "COD795",
  "price": 35,
  "status": true,
  "stock": 1423,
  "category": "Comestibles",
  "thumbnails": []
}

### PUT Product

PUT http://localhost:8080/api/products/67a03133be2c0dc3707701c5
Content-Type: application/json

{
  "title": "Sidra Mza Roja"
}

### DELETE Product
DELETE http://localhost:8080/api/products/67a0c5a07428406dbf415a5e